import type { GoalWithProgress } from "@greatstone/shared";

/** Test fixture: an active goal, half done by linked tasks. */
export function makeGoal(overrides: Partial<GoalWithProgress> = {}): GoalWithProgress {
  return {
    id: "g1",
    companyId: "c1",
    title: "Goal",
    description: null,
    level: "company",
    kind: null,
    status: "active",
    parentId: null,
    ownerAgentId: null,
    ownerUserId: null,
    targetDate: null,
    doneWhen: null,
    targetValue: null,
    currentValue: null,
    unit: null,
    baselineValue: null,
    baselineDate: null,
    kpiDirection: null,
    amberThresholdPct: null,
    redThresholdPct: null,
    budgetPlannedCents: null,
    budgetSpentCents: null,
    budgetCurrency: null,
    benchmarkNote: null,
    sourceIssueId: null,
    sourceDocumentKey: null,
    sourceBulletId: null,
    createdAt: new Date(2026, 8, 1),
    updatedAt: new Date(2026, 8, 1),
    progress: { percent: 50, source: "issues", done: 2, open: 2, blocked: 0, total: 4 },
    blockers: [],
    latestCheckIn: null,
    kpiStatus: null,
    ragRollup: { status: null, red: 0, amber: 0, green: 0, noStatus: 0 },
    latestReading: null,
    ...overrides,
  };
}
